import { SearchIndexAdditionalFieldType } from './interfaces/search-index-additional-field-type';
import { FacetSettings } from './interfaces/facet-settings';

export  class SearchFacetExtensions {
    static isValueFacet(settings: FacetSettings) {
        if (settings.RangeType === this.AutoGeneratedFacet) {
            if (settings.FacetType === SearchIndexAdditionalFieldType.DateAndTime) {
                // UX: When no data step is set - the Date field should be displayed as interval facet with a day interval.
                return false;
            }

            if (settings.FacetType === SearchIndexAdditionalFieldType.NumberWhole
                || settings.FacetType === SearchIndexAdditionalFieldType.NumberDecimal) {
                // UX: When no number step is set - the Number field should be displayd as a value facet.
                return settings.NumberStep == null;
            }

            return true;
        }

        return false;
    }

    static AutoGeneratedFacet = 0;
}
